### ISSUE TITLE
Array2D.initialize: in the provided function row and column indices are wrong

### ISSUE THREAD

**Issue by pogiaron** [JoshuaHall/elm-2d-array#1]
In the first example indices are correct in the provided function, but in the second example, you can see that the indices are wrong.
I think the problem occurs when rows are greater than cols.
```
Array2D.initialize 4 4 (\row col -> (String.fromInt row ++ ":" ++ String.fromInt col))
["0:0","0:1","0:2","0:3"
,"1:0","1:1","1:2","1:3"
,"2:0","2:1","2:2","2:3"
,"3:0","3:1","3:2","3:3"
]

Array2D.initialize 4 2 (\row col -> (String.fromInt row ++ ":" ++ String.fromInt col))
["0:0","0:1"
,"0:0","0:1"
,"1:0","1:1"
,"1:0","1:1
]
```

**Comment by JoshuaHall** [comment]
Thanks a lot for finding this! I should have added tests for this earlier 😄 I've published a new `1.0.1` release which should fix this issue and adds some tests that cover your example.
