### ISSUE TITLE
Array2D.get does not always return Nothing when it should

### ISSUE THREAD

**Issue by adauguet** [JoshuaHall/elm-2d-array#2]
Hi!
I recently had a bug when searching for neighbours in an Array2D.
It looks like when calling `Array2D.get` with a negative column will return values from the previous row, if any, starting from the end.
```elm
array = Array2D.fromRows <|
    Array.fromList
        [ Array.fromList [ 1, 2 ]
        , Array.fromList [ 3, 4 ]
        ]

result = Maybe.map (Array.get 1 -1) array -- returns (Just 2) instead of Nothing
```

Please see the following Ellie: [https://ellie-app.com/gbCSDCn2r9ka1](https://ellie-app.com/gbCSDCn2r9ka1)

Is it intended behaviour?

[EDIT]

If is not intended behaviour, I guess I could add a check against `row`/`column` begin greater than `numRows`/`numColumns` here:
```elm
get : Int -> Int -> Array2D a -> Maybe a
get row column (InternalArray2D array) =
    if row >= array.numRows || column >= array.numColumns then
        Nothing

    else
        Array.get
            (indexFromRowAndColumn (InternalArray2D array) row column)
            array.array
```

**Comment by JoshuaHall** [comment]
Hey, I think I fixed the issue in the `1.0.2` release; thank you for pointing this out! I added another check to ensure the row/column is not less than zero. I don't know how I missed this earlier :)
